Change imports (and other) from ubuntu-phonedations to ubports
ubports/nuntium pull request #5
Opened 2020-11-07 21:58 UTC by jezek

This PR proposes to cut ties from ubuntu-phonedations repo for good. This step is essential for further development of ```nuntium```. For example without this, any change to [nuntium/ofono package](https://github.com/ubports/nuntium/tree/xenial/ofono) wouldn't have any effect, cause ```nuntium``` [builds against ubutu-ponedations packages](https://github.com/ubports/nuntium/blob/38940464d532a145412c47d8901c1a74fb662eff/cmd/nuntium/main.go#L29-L30). I've splitted this changes into some commits for better clarity, with some insights in commit descriptions.

2020-11-08 16:15 UTC, lduboeuf commented
tested on BQ4.5, no regressions found and also the MMSEnabled toggle is working now. ( the MMS is not retrieved as expected when set to off , before it was not the case )

2020-11-09 21:38 UTC, lduboeuf commented
I would split this PR in two, one with the cherry-pick from phondation and the other for namespace migration

2020-11-10 15:10 UTC, jezek commented
@lduboeuf 
> I would split this PR in two, one with the cherry-pick from phondation and the other for namespace migration ( just say that but i'm not the maintainer )

Yep, it would be more logical. Maybe it's also fine this way. Will do, as the higher-ups say. :slightly_smiling_face:

2020-11-10 15:13 UTC, jezek commented on cmd/nuntium/mediator.go
> +	log.Printf("mmsEnabled: mms option value: %v", mms.Value.(bool))
Now I know the code is working, this log could be commented out.

2020-11-10 22:43 UTC, dobey commented
> Yep, it would be more logical. Maybe it's also fine this way. Will do, as the higher-ups say.

I think it would be better, or at least the first change should be to merge in the changes from the phonedations repo, by adding it as a remote and doing a `merge` or a `cherry-pick` rather than applying a diff, so that the commit history is properly preserved. The history should be compatible enough to do so, at least. Then all the imports and references to phonedations can be added separately, so there's a clear line of separation between the two.

Thanks!

2020-11-10 22:44 UTC, dobey requested changes
See previous comment.

2020-11-12 16:49 UTC, jezek commented
@dobey You mean like this, or split the PR into two (mmsEnabled, imports)?

2020-11-12 17:24 UTC, dobey commented
> You mean like this, or split the PR into two (mmsEnabled, imports)?

Two separate PRs would probably be better. One for merging the "upstream" changes in (like maybe adding the remote and creating a new branch based on its master, and just PR that into xenial here), and a second with your changes. Or maybe three PRs since the "error logging and refactor mmsEnabled" bit is also separate from the replacing ubuntu-phonedations bit.

Thanks!

2020-11-12 19:45 UTC, Flohack74 commented on README.md
> +* This project is a continuitation of [the ubuntu-phonedations nuntium project](https://github.com/ubuntu-phonedations/nuntium/).
Its _continuation_

2020-11-14 22:19 UTC, jezek commented
@dobey 
> Two separate PRs would probably be better. One for merging the "upstream" changes in (like maybe adding the remote and creating a new branch based on its master, and just PR that into xenial here), and a second with your changes. Or maybe three PRs since the "error logging and refactor mmsEnabled" bit is also separate from the replacing ubuntu-phonedations bit.

To be sure, we are on the same page.

I've added upstream (ubuntu-phonedations/master) and then (after resolving some conflicts, due to new merged code in xenial) merged with xenial (see https://github.com/jezek/nuntium/tree/xenial_-_merge-upstream). This would be the PR no 1. 

Then the second would be error logging and refactoring of mms-enabled logic. 

An then the third would be this (without the first two commits). Right?

2020-11-16 19:03 UTC, dobey commented
> Right?

Sounds good, yeah. Main concern was to preserve the upstream history. Thanks.

2020-11-19 16:04 UTC, jezek commented on README.md
> +* This project is a continuitation of [the ubuntu-phonedations nuntium project](https://github.com/ubuntu-phonedations/nuntium/).
fixed

2020-11-19 16:07 UTC, jezek commented
@dobey Sorry for my delay. I've added PRs #6 & #7 , which should precede this one.

2020-11-21 17:06 UTC, jezek commented
Ok, now the PRs #6 & #7 are merged to xenial branch. What other changes need to be done to accept this PR?

2020-11-23 21:36 UTC, dobey approved these changes
Looks good. Thanks!

2020-11-23 21:37 UTC, merged